package com.nutritrackpro.data.nutriCoachTips

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import com.nutritrackpro.data.patients.Patient
import java.time.LocalDateTime

/**
 * Represents a food intake questionnaire made by a patient.
 *
 * This data class is annotated with @Entity to mark it as a Room database table.
 * The table name is "nutri_coach_tips".
 */
@Entity(tableName = "nutri_coach_tips",
    foreignKeys = [
        ForeignKey(
            entity = Patient::class,
            parentColumns = ["userId"],
            childColumns = ["userId"],
            onDelete = ForeignKey.CASCADE
        )],
    indices = [Index("userId")]
)
data class NutriCoachTips(
    /**
     * Unique identifier of the patient the nutri coach tips belongs to.
     * It is automatically generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    /**
     * The user id of the user that the tip belongs to
     */
    val userId: String,
    /**
     * The tip generated by the AI
     */
    val tip: String,
    /**
     * The time of the tip add to the database
     */
    val createdAt: Long = System.currentTimeMillis()
)